title: "Fuses"
baseurl: "/links" 
url: "https://bandet-fuses.github.io"

# This is the important part:
theme: [] 
plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .jekyll-cache
  - vendor/